#!/bin/bash

DISTRO=""
Debian='debian
os'

get_distro()
{
	UNAME=$(uname | tr "[:upper:]" "[:lower:]")
	# If Linux, try to determine specific distribution
	if [ "$UNAME" == "linux" ]; then
		# If available, use LSB to identify distribution
		if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
			DISTRO=$(lsb_release -i | cut -d: -f2 | sed s/'^\t'//)
		# Otherwise, use release info file
		else
			DISTRO=$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v "lsb" | cut -d'/' -f3 | cut -d'-' -f1 | cut -d'_' -f1)
		fi
	fi
	# For everything else (or if above failed, just use generic identifier
	[ "$DISTRO" == "" ] && DISTRO=$UNAME
	unset UNAME
}

update()
{
	if [  "$DISTRO" = "$Debian" -o "$DISTRO" = "Kali" ] ; then
		if [ "$USER" = "root" ] ; then
		apt-get update
		apt-get upgrade
		else echo "You must be logged in as root to run this script. Type 'su' then enter your password and try again"
		fi
	elif [ "$DISTRO" = "LinuxMint" -o "$DISTRO" = "Ubuntu" ] ; then
		sudo apt-get update
		sudo apt-get upgrade
	elif [ "$DISTRO" = "Fedora" ] ; then
		sudo dnf update
	elif [ "$DISTRO" = "SUSE LINUX" ] ; then
		sudo zypper update
	elif [ "$DISTRO" = "ManjaroLinux" ] ; then
		sudo pacman -Syyu
	else echo "Distribution " $DISTRO " not yet supported"
	fi
}

get_distro
update
